### ISSUE TITLE
Unexpected token error in type.

### ISSUE THREAD

**Issue by trusktr** [Kuniwak/jsdoctypeparser#6]
Hi, I was trying to do

```js
/*
 * @function contextWithPerspective
 * @param {integer} perspective
 * @returns {famous/core/Context} The context with the applied perspective.
 */
```

in a comment, and the `@returns` type errors out because of the slashes. I'm using [`dox`](https://github.com/tj/dox) which uses jsdoctypeparser to parse types.

The reason I was trying to use `famous/core/Context` is to indicate where the class is loacated in the famous library. In famo.us, you would `import Context from 'famous/core/Context'`, so I thought I could reflect this fact.

As a workaround, I'm thinking perhaps just doing

```js
/*
 * @function contextWithPerspective
 * @param {integer} perspective
 * @returns {Context} The `famous/core/Context` with the applied perspective.
 */
```

I haven't tried jsdoc, will jsdoc error out on this? Maybe jsdoctypeparser can have a non-strict option that will convert non-conforming characters to hyphens for the generated link?

EDIT: I can just use `famous.core.Context` for now.

**Comment by Kuniwak** [comment]
Hi @trusktr .

You can use a file path as the type by the module token:

```javascript
/**
 * @param {module: famouse/core/Context} The `famous/core/Context` with the applied perspective.
 */
```

I referred to [JSDoc3 type expression](http://usejsdoc.org/tags-type.html#overview) and [Google Closure Compiler type expression](https://developers.google.com/closure/compiler/docs/js-for-compiler#types) for implementing the jsdoctypeparser. And unfortunately, there are no specs for using a file path as the type.
But, I implemented the spec, because I found the similar specs from [hegemonic/catharsis](https://github.com/hegemonic/catharsis/blob/master/test/specs/jsdoc/jsdoc.js#L83) that is the internal type expression parser of JSDoc3.

**Comment by trusktr** [comment]
Wow, very nice!! Definitely make sure this detail is highly visible in the docs. :)
